title: Voeg TestMeshPro tekst en knoppen toe en positioneer deze
hero_image: images/banner.png
description: Het toevoegen, configureren en positioneren van tekst en knoppen met TextMeshPro
version: 4
listed: false
copyedit: false
last_tested: "2021-11-18"
steps:
  - 
    title: Voeg TestMeshPro tekst en knoppen toe en positioneer deze
