title: Add and position TestMeshPro text and buttons
hero_image: images/banner.png
description: Add, configure, and position text and buttons with TextMeshPro
version: 4
listed: false
copyedit: false
last_tested: "2021-11-18"
steps:
  - title: Add and position TestMeshPro text and buttons
 
