title: Ajouter et positionner le texte et les boutons TestMeshPro
hero_image: images/banner.png
description: Add, configure, and position text and buttons with TextMeshPro
version: 4
listed: false
copyedit: false
last_tested: "2021-11-18"
steps:
  - 
    title: Ajouter et positionner le texte et les boutons TestMeshPro
